feign:
    client:
        config:
            default:
                connectTimeout: 160000000
                readTimeout: 160000000
ribbon:
    eureka:
        enabled: true
server:
    port: 8083
    ssl:
        enabled: true
        key-alias: relevebancaire-docker
        key-store: classpath:relevebancaire-docker-keystore.p12
        key-store-password: secret
        key-store-type: PKCS12
    servlet:
        context-path: /api/v3
spring:
    application:
        name: activiti-workflow
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: ${DB_PASSWORD}
        url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
    instance:
        preferIpAddress: true
        hostname: eureka-0
    client:
        serviceUrl:
            defaultZone: https://eureka-0.eureka.default.svc.cluster.local:8761/eureka
        registerWithEureka: true
        fetchRegistry: true
