feign:
    client:
        config:
            default:
                connectTimeout: 160000000
                readTimeout: 160000000
ribbon:
    eureka:
        enabled: true
server:
    port: 8083
    ssl:
        enabled: true
        key-alias: relevebancaire-docker
        key-store: classpath:relevebancaire-docker-keystore.p12
        key-store-password: secret
        key-store-type: PKCS12
    servlet:
        context-path: /api/v3
spring:
    application:
        name: activiti-workflow
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://mysqldb:3306/releve-bancaire-cdg?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: https://localhost:8761/eureka
    instance:
        hostname: localhost
