feign:
    client:
        config:
            default:
                connectTimeout: 160000000
                readTimeout: 160000000
ribbon:
    eureka:
        enabled: true
server:
    address: 127.0.0.1
    port: 8083
    servlet:
        context-path: /api/v3
spring:
    application:
        name: activiti-workflow
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/releve-bancaire-cdg?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

